import Head from 'next/head'
import {increment,decrement,getcount} from "../blockchainservice.jsx"
import { useState } from 'react';

export default function Home() {
  const [count,SetCount] = useState("");
  const handleinc = async () => {
    const incre = await increment();
  };
  const handledec = async () => {
    const decre = await decrement();
  };
 const getcounts = async () => {
  const getc = await getcount();
  console.log("counts",getc)
  
 }
 getcounts();
  return (
    <>
      <Head>
        <title>Counter App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1 className='text-center'>Counter App</h1>
      <div className='text-center space-x-10'>
        <button className='text-center' onClick={handleinc}>+</button>
        {count}
        <button onClick={handledec} className='text-center'>-</button>
      </div>
    </>
  )
}
